# Generated by Django 5.2.7 on 2026-01-27 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('hamster', 'Hamster'), ('guinea_pig', 'Guinea Pig'), ('reptile', 'Reptile'), ('fish', 'Fish'), ('other', 'Other')], max_length=20)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=6)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('microchip_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pets/')),
                ('allergies', models.TextField(blank=True)),
                ('medical_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'is_active'], name='pets_owner_i_771429_idx'), models.Index(fields=['species'], name='pets_species_a3549a_idx')],
            },
        ),
    ]
